// Mock data for development and testing
import { Emergency, Paramedic, EventStats, Location } from "../types";

// Mock event locations
export const mockLocations: Location[] = [
  { lat: 40.7589, lng: -73.9851, address: "Main Stage Area" },
  { lat: 40.7592, lng: -73.9847, address: "Food Court Section B" },
  { lat: 40.7585, lng: -73.9855, address: "VIP Lounge East" },
  { lat: 40.7595, lng: -73.9845, address: "North Entrance Gate" },
  { lat: 40.7582, lng: -73.9858, address: "South Parking Lot" },
  { lat: 40.7598, lng: -73.9842, address: "Merchandise Tent 3" },
];

export const mockParamedics: Paramedic[] = [
  {
    id: "p1",
    name: "Dr. Sarah Johnson",
    status: "busy",
    location: mockLocations[0],
    assignedIncidentId: "e1",
  },
  {
    id: "p2",
    name: "Mike Chen",
    status: "available",
    location: mockLocations[1],
  },
  {
    id: "p3",
    name: "Dr. Emily Rodriguez",
    status: "busy",
    location: mockLocations[2],
    assignedIncidentId: "e2",
  },
  {
    id: "p4",
    name: "James Wilson",
    status: "available",
    location: mockLocations[3],
  },
  {
    id: "p5",
    name: "Dr. Lisa Park",
    status: "offline",
    location: mockLocations[4],
  },
];

export const mockEmergencies: Emergency[] = [
  {
    id: "e1",
    reporterId: "u1",
    reporterName: "John Doe",
    reporterPhone: "+1-555-0101",
    location: mockLocations[0],
    status: "on-the-way",
    severity: "high",
    description: "Person experiencing chest pain and shortness of breath",
    category: "Cardiac",
    assignedParamedicId: "p1",
    assignedParamedicName: "Dr. Sarah Johnson",
    createdAt: new Date(Date.now() - 10 * 60000).toISOString(),
    updatedAt: new Date(Date.now() - 3 * 60000).toISOString(),
    responseTime: 7,
  },
  {
    id: "e2",
    reporterId: "u2",
    reporterName: "Jane Smith",
    reporterPhone: "+1-555-0102",
    location: mockLocations[2],
    status: "assigned",
    severity: "medium",
    description: "Sprained ankle, unable to walk",
    category: "Orthopedic",
    assignedParamedicId: "p3",
    assignedParamedicName: "Dr. Emily Rodriguez",
    createdAt: new Date(Date.now() - 5 * 60000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 60000).toISOString(),
    responseTime: 3,
  },
  {
    id: "e3",
    reporterId: "u3",
    reporterName: "Alex Brown",
    reporterPhone: "+1-555-0103",
    location: mockLocations[1],
    status: "requested",
    severity: "critical",
    description: "Severe allergic reaction, difficulty breathing",
    category: "Allergic",
    createdAt: new Date(Date.now() - 2 * 60000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 60000).toISOString(),
  },
  {
    id: "e4",
    reporterId: "u4",
    reporterName: "Maria Garcia",
    reporterPhone: "+1-555-0104",
    location: mockLocations[5],
    status: "resolved",
    severity: "low",
    description: "Minor cut requiring bandaging",
    category: "Minor Injury",
    assignedParamedicId: "p2",
    assignedParamedicName: "Mike Chen",
    createdAt: new Date(Date.now() - 45 * 60000).toISOString(),
    updatedAt: new Date(Date.now() - 30 * 60000).toISOString(),
    resolvedAt: new Date(Date.now() - 30 * 60000).toISOString(),
    responseTime: 4,
  },
  {
    id: "e5",
    reporterId: "u5",
    reporterName: "Tom Anderson",
    reporterPhone: "+1-555-0105",
    location: mockLocations[4],
    status: "resolved",
    severity: "medium",
    description: "Heat exhaustion, dehydration",
    category: "Heat-related",
    assignedParamedicId: "p4",
    assignedParamedicName: "James Wilson",
    createdAt: new Date(Date.now() - 60 * 60000).toISOString(),
    updatedAt: new Date(Date.now() - 45 * 60000).toISOString(),
    resolvedAt: new Date(Date.now() - 45 * 60000).toISOString(),
    responseTime: 6,
  },
];

export const mockEventStats: EventStats = {
  totalIncidents: 12,
  activeIncidents: 3,
  resolvedIncidents: 9,
  averageResponseTime: 5.2,
  availableParamedics: 2,
  busyParamedics: 2,
};
